//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GateKeeperAdmin {
    
    public partial class AdminToolMasterPage {
        protected System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolderHead;
        protected System.Web.UI.HtmlControls.HtmlForm MasterForm;
        protected System.Web.UI.WebControls.HyperLink lnkHome;
        protected GateKeeperAdmin.UserControls.TabsControl NavTabControl;
        protected GateKeeperAdmin.WebControls.LoginControl LoginCtr;
        protected System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolderMaster;
        protected System.Web.UI.WebControls.HyperLink HomeTab;
        protected System.Web.UI.WebControls.HyperLink ReqHistTab;
        protected System.Web.UI.WebControls.HyperLink ActivitiesTab;
        protected System.Web.UI.WebControls.HyperLink ReportsTab;
        protected System.Web.UI.WebControls.HyperLink AdminTab;
        protected System.Web.UI.WebControls.Image Image1;
    }
}
