//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GateKeeperAdmin.Administrator {
    
    public partial class ResetCache {
        protected System.Web.UI.WebControls.Label lblStatus;
        protected System.Web.UI.HtmlControls.HtmlGenericControl AdminBoxDiv;
        protected System.Web.UI.WebControls.Button btnResetLiveCache;
        protected System.Web.UI.WebControls.Button btnResetPreviewCache;
        protected System.Web.UI.WebControls.Button btnResetCGPU;
        protected System.Web.UI.WebControls.Button btnResetCGSPU;
        protected System.Web.UI.HtmlControls.HtmlTable ImportDoc;
        protected System.Web.UI.WebControls.FileUpload FileUploadImport;
        protected System.Web.UI.WebControls.Button btnImport;
        protected System.Web.UI.WebControls.Repeater ReqRepeater;
    }
}
