//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GateKeeperAdmin.ProcessingActivities {
    
    public partial class Activities {
        protected System.Web.UI.HtmlControls.HtmlGenericControl ActiveTabDiv;
        protected System.Web.UI.WebControls.Image ErrorImage1;
        protected System.Web.UI.HtmlControls.HtmlGenericControl FailedTabDiv;
        protected System.Web.UI.WebControls.Image ErrorImage2;
        protected System.Web.UI.HtmlControls.HtmlGenericControl ActionsDiv;
        protected System.Web.UI.WebControls.ImageButton ActivateButton;
        protected System.Web.UI.WebControls.ImageButton DeactivateButton;
        protected System.Web.UI.WebControls.ImageButton ClearButton;
        protected System.Web.UI.HtmlControls.HtmlGenericControl StatusDiv;
        protected System.Web.UI.WebControls.Repeater BatchRepeater;
    }
}
