//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GateKeeperAdmin.Reports {
    
    public partial class ViewReports {
        protected System.Web.UI.WebControls.DropDownList dropViewReports;
        protected System.Web.UI.WebControls.ImageButton ibtnGo;
        protected System.Web.UI.HtmlControls.HtmlGenericControl ScheduleDiv;
        protected System.Web.UI.HtmlControls.HtmlGenericControl idDataTabled;
        protected System.Web.UI.WebControls.Panel pnlTitle;
        protected System.Web.UI.WebControls.Label lblTitle;
        protected System.Web.UI.WebControls.Label lblBatchName;
        protected System.Web.UI.WebControls.Label lblStatus;
        protected System.Web.UI.WebControls.Label lblDateTime;
        protected System.Web.UI.WebControls.Label lblUserName;
        protected System.Web.UI.WebControls.Repeater rptViewReports;
    }
}
