//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GateKeeperAdmin.Reports {
    
    public partial class ViewLocation {
        protected System.Web.UI.HtmlControls.HtmlGenericControl ScheduleDiv;
        protected System.Web.UI.WebControls.TextBox txtCdrId;
        protected System.Web.UI.WebControls.ImageButton ibtnGo;
        protected System.Web.UI.HtmlControls.HtmlGenericControl idDataTabled;
        protected System.Web.UI.WebControls.Label lblCdrid;
        protected System.Web.UI.WebControls.Label lblDocType;
        protected System.Web.UI.WebControls.DropDownList dropDocType;
        protected System.Web.UI.WebControls.Label lblGK;
        protected System.Web.UI.WebControls.Label lblStaging;
        protected System.Web.UI.WebControls.Label lblPreview;
        protected System.Web.UI.WebControls.Label lblLive;
        protected System.Web.UI.WebControls.Label lblGKReqId;
        protected System.Web.UI.WebControls.Label lblGKDate;
        protected System.Web.UI.WebControls.Label lblStagingReqId;
        protected System.Web.UI.WebControls.Label lblStagingDate;
        protected System.Web.UI.WebControls.Label lblPreviewReqId;
        protected System.Web.UI.WebControls.Label lblPreviewDate;
        protected System.Web.UI.WebControls.Label lblLiveReqId;
        protected System.Web.UI.WebControls.Label lblLiveDate;
        protected System.Web.UI.WebControls.Repeater rptLocation;
    }
}
