//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GateKeeperAdmin.UserControls {
    
    public partial class TabsControl {
        protected System.Web.UI.WebControls.HyperLink HomeTab;
        protected System.Web.UI.WebControls.HyperLink ReqHistTab;
        protected System.Web.UI.WebControls.HyperLink ActivitiesTab;
        protected System.Web.UI.WebControls.HyperLink ReportsTab;
        protected System.Web.UI.WebControls.HyperLink AdminTab;
    }
}
