//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GateKeeperAdmin.RequestHistory {
    
    public partial class Popup {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlLink lnkStyleSheets;
        protected System.Web.UI.WebControls.Image imgNci;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.HtmlControls.HtmlGenericControl idDataTabled;
        protected System.Web.UI.WebControls.Label lblEntry;
        protected System.Web.UI.WebControls.Label lblHistory;
        protected System.Web.UI.WebControls.Repeater rptTypeCount;
    }
}
