//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GateKeeperAdmin.RequestHistory {
    
    public partial class RequestDetails {
        protected System.Web.UI.WebControls.Label RequestIdLbl;
        protected System.Web.UI.WebControls.Label BatchIdLbl;
        protected System.Web.UI.WebControls.Panel pnlInfo;
        protected System.Web.UI.WebControls.Label lblNumEntries;
        protected System.Web.UI.HtmlControls.HtmlAnchor aPopup;
        protected System.Web.UI.WebControls.Label RequestIdLbl1;
        protected System.Web.UI.HtmlControls.HtmlGenericControl ScheduleDiv;
        protected System.Web.UI.HtmlControls.HtmlGenericControl ActionsDiv;
        protected System.Web.UI.WebControls.DropDownList ActionDropDown;
        protected System.Web.UI.WebControls.CustomValidator CustomValidator1;
        protected System.Web.UI.WebControls.TextBox BatchNameTxt;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
        protected System.Web.UI.WebControls.ValidationSummary ValidationSummary1;
        protected System.Web.UI.WebControls.ImageButton ActionGoButton;
        protected System.Web.UI.WebControls.ImageButton ScheduleAllButton;
        protected System.Web.UI.WebControls.ImageButton ClearFiltersButton;
        protected System.Web.UI.WebControls.ImageButton ExportButton;
        protected System.Web.UI.HtmlControls.HtmlGenericControl NoActionsDiv;
        protected System.Web.UI.WebControls.ImageButton ImageButton1;
        protected System.Web.UI.WebControls.Label RequestDocCount;
        protected System.Web.UI.WebControls.LinkButton lnkSelectAll;
        protected System.Web.UI.WebControls.LinkButton lnkClearAll;
        protected System.Web.UI.WebControls.LinkButton PacketNumLinkBtn;
        protected System.Web.UI.WebControls.LinkButton GroupIdLinkBtn;
        protected System.Web.UI.WebControls.LinkButton CdrIdLinkBtn;
        protected System.Web.UI.WebControls.LinkButton ReqTypeLinkBtn;
        protected System.Web.UI.WebControls.DropDownList RequestTypeDropDown;
        protected System.Web.UI.WebControls.LinkButton DocTypeLinkBtn;
        protected System.Web.UI.WebControls.DropDownList DocTypeDropDown;
        protected System.Web.UI.WebControls.LinkButton DocStatusLinkBtn;
        protected System.Web.UI.WebControls.DropDownList StatusDropDown;
        protected System.Web.UI.WebControls.LinkButton DepStatusLinkBtn;
        protected System.Web.UI.WebControls.DropDownList DepStatusDropDown;
        protected System.Web.UI.WebControls.LinkButton LocationLnkBtn;
        protected System.Web.UI.WebControls.DropDownList LocationDropDown;
        protected System.Web.UI.WebControls.Repeater ReqRepeater;
        protected System.Web.UI.HtmlControls.HtmlGenericControl ConfirmationDiv;
        protected System.Web.UI.WebControls.Label ActionLabel;
        protected System.Web.UI.WebControls.Label BatchNameLbl;
        protected System.Web.UI.WebControls.ImageButton ScheduleBttn;
        protected System.Web.UI.WebControls.Repeater RepeaterConfirm;
    }
}
