//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GateKeeperAdmin.RequestHistory {
    
    public partial class RequestHistory {
        protected System.Web.UI.WebControls.DropDownList NumMonthDropDown;
        protected System.Web.UI.WebControls.ImageButton ActionGoButton;
        protected System.Web.UI.WebControls.ImageButton ClearFiltersButton;
        protected System.Web.UI.WebControls.TextBox CdrIdTextBox;
        protected System.Web.UI.WebControls.ImageButton CdrGoButton;
        protected System.Web.UI.WebControls.Label RequestDocCount;
        protected System.Web.UI.WebControls.LinkButton ReqDateLinkBtn;
        protected System.Web.UI.WebControls.LinkButton ReqIdLinkBtn;
        protected System.Web.UI.WebControls.LinkButton ReqStatusLinkBtn;
        protected System.Web.UI.WebControls.DropDownList RequestStatusDropDown;
        protected System.Web.UI.WebControls.LinkButton PubDestinationLinkBtn;
        protected System.Web.UI.WebControls.DropDownList PubDestinationDropDown;
        protected System.Web.UI.WebControls.LinkButton ExternalReqIdLinkBtn;
        protected System.Web.UI.WebControls.Repeater ReqRepeater;
    }
}
