//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GateKeeperAdmin.RequestHistory {
    
    public partial class RequestBatchHistory {
        protected System.Web.UI.WebControls.Label RequestIdLbl;
        protected System.Web.UI.HtmlControls.HtmlGenericControl ScheduleDiv;
        protected System.Web.UI.HtmlControls.HtmlGenericControl idDataTabled;
        protected System.Web.UI.WebControls.Label lblEntry;
        protected System.Web.UI.WebControls.Label lblBatchName;
        protected System.Web.UI.WebControls.Label lblStatus;
        protected System.Web.UI.WebControls.Label lblDateTime;
        protected System.Web.UI.WebControls.Label lblUserName;
        protected System.Web.UI.WebControls.Label lblHistory;
        protected System.Web.UI.WebControls.Repeater rptRequestBatchHistory;
    }
}
