//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GateKeeperAdmin.RequestHistory {
    
    public partial class RequestDataSummary {
        protected System.Web.UI.WebControls.Label sectionLabel;
        protected System.Web.UI.WebControls.Label Cdrid;
        protected System.Web.UI.WebControls.Label RequestIdLabel;
        protected System.Web.UI.WebControls.Label DateLabel;
        protected System.Web.UI.WebControls.Label CDRVersionLabel;
        protected System.Web.UI.WebControls.Label XMLLink;
        protected System.Web.UI.WebControls.HyperLink DocumentHistoryLink;
    }
}
