//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GateKeeperAdmin.RequestHistory {
    
    public partial class RequestCDRID {
        protected System.Web.UI.WebControls.Label RequestDataIdLbl;
        protected System.Web.UI.WebControls.Label CDRIDLbl;
        protected System.Web.UI.WebControls.Label CDRVersionLbl;
        protected System.Web.UI.WebControls.Label PacketNumLbl;
        protected System.Web.UI.WebControls.Label DateLbl;
        protected System.Web.UI.WebControls.Label ActionTypeLbl;
        protected System.Web.UI.WebControls.Label LocationLbl;
        protected System.Web.UI.WebControls.Label DocTypeLbl;
        protected System.Web.UI.WebControls.Label StatusLbl;
        protected System.Web.UI.WebControls.Label DependencyStatusLbl;
        protected System.Web.UI.WebControls.Label GroupIdLbl;
        protected System.Web.UI.HtmlControls.HtmlGenericControl ScheduleActionsDiv;
        protected System.Web.UI.WebControls.TextBox BatchNameTxtBox;
        protected System.Web.UI.WebControls.RequiredFieldValidator valrBatchName;
        protected System.Web.UI.WebControls.CheckBox PushToStagingPreviewChkbx;
        protected System.Web.UI.WebControls.CheckBox PushToLiveChkbx;
        protected System.Web.UI.WebControls.CustomValidator valxCheckBoxes;
        protected System.Web.UI.WebControls.ValidationSummary valsSummary;
        protected GateKeeperAdmin.RequestHistory.RequestDataSummary GateKeeperBox;
        protected GateKeeperAdmin.RequestHistory.RequestDataSummary StagingBox;
        protected GateKeeperAdmin.RequestHistory.RequestDataSummary PreviewBox;
        protected GateKeeperAdmin.RequestHistory.RequestDataSummary LiveBox;
    }
}
